server_ip = "120.79.196.42"
server_port = 3000

user = "xiangzhijun"
token = "123456"

ping_interval=10
pong_timeout=15

conn_pool_count=0


[[proxy]]
name = "http_proxy"
type = "http"
encryption = true
local_ip = "127.0.0.1"
local_port = 80

domain="120.79.196.42"
url="/"

[[proxy]]
name = "tcp_proxy"
type = "tcp"
<<<<<<< HEAD
encryption = true
local_ip = "127.0.0.1"
local_port = 5000

[entranet]
bind_ip="0.0.0.0"
bind_port=5000
=======
encryption = false
local_ip = "10.69.152.61"
local_port = 22
remote_port=4000
>>>>>>> 97f934fe977a85455bb64a9e6d40513e5fc2473e
