server_ip = "120.79.196.42"
server_port = 3000

user = "xiangzhijun"
token = "123456"

ping_interval=10
pong_timeout=15

conn_pool_count=0


[[proxy]]
name = "http_proxy"
type = "http"
encryption = true
local_ip = "127.0.0.1"
local_port = 80

domain="www.xiangzhijun.cn"
url="/"

[[proxy]]
name = "tcp_proxy"
type = "tcp"
encryption = true
local_ip = "127.0.0.1"
local_port = 5000

[[proxy]]
name = "https_proxy"
type = "https"
encryption = false
local_ip = "0.0.0.0"
local_port = 443

domain = "https.xiangzhijun.cn"
url = "/"

[entranet]
bind_ip="0.0.0.0"
bind_port=5000

