bind_ip = "127.0.0.1"
bind_port = 3000
user_token_file = "./config/usertoken.json"
auth_timeout = 600

[http_proxy]
visit_ip = "127.0.0.1"
visit_port = 8080

[https_proxy]
visit_ip = "127.0.0.1"
visit_port = 443
