bind_ip = "120.79.196.42"
bind_port = 3000
user_token_file = "./config/usertoken.json"
auth_timeout = 600

ping_timeout=15

[http_proxy]
visit_ip = "120.79.196.42"
visit_port = 8080

[https_proxy]
visit_ip = "127.0.0.1"
visit_port = 443
